package br.com.faturamed.domain;

public enum TipoDivergencia {
    CONFORME,
    NAO_ENCONTRADO,
    DUPLICIDADE,
    QUANTIDADE_DIVERGENTE,
    VALOR_DIVERGENTE,
    MEDICO_DIVERGENTE,
    DATA_DIVERGENTE,
    PROCEDIMENTO_DIVERGENTE,
    FATURADO_SEM_PRODUCAO,
    PRODUZIDO_SEM_FATURAMENTO
}
