spring:
  application:
    name: faturamed
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/faturamed}
    username: ${DB_USER:faturamed}
    password: ${DB_PASSWORD:faturamed}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
